name = "nuxt-better-auth-demo"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "better-auth-db"
database_id = "19843a99-07d8-4c3b-b479-b48ba3792ce3"
